Repository GDG-on-Campus-KHU/SDGP_team2_BE, pull requests merged in 2025-05, with the labels that each got.

#41 [Refactor] application.yaml 에서 oauth 관련 설정 부분 위치 수정
  src/main/java/com/gdg/coffee/domain/auth/service/GoogleOAuthService.java
Labels: 🐞BUG

#42 [Fix] api filter
  src/main/java/com/gdg/coffee/global/config/SecurityConfig.java
  src/main/java/com/gdg/coffee/global/security/jwt/JwtAuthenticationFilter.java
Labels: 🐞BUG

#44 [Fix] Cors 에러 해결
  src/main/java/com/gdg/coffee/global/config/CorsConfig.java
  src/main/java/com/gdg/coffee/global/config/SecurityConfig.java
Labels: 🐞BUG

#45 [Fix] 구글 소셜 로그인 로직 변경
  src/main/java/com/gdg/coffee/domain/auth/controller/AuthController.java
  src/main/java/com/gdg/coffee/domain/auth/service/GoogleOAuthService.java
  src/main/java/com/gdg/coffee/global/config/SecurityConfig.java
Labels: ✂️CHORE

#47 [Add] API to check if the logged-in member has a cafe
  docker-compose.yaml
  src/main/java/com/gdg/coffee/domain/cafe/controller/CafeController.java
  src/main/java/com/gdg/coffee/domain/cafe/exception/CafeErrorCode.java
  src/main/java/com/gdg/coffee/domain/cafe/exception/CafeSuccessCode.java
  src/main/java/com/gdg/coffee/domain/cafe/repository/CafeRepository.java
  src/main/java/com/gdg/coffee/domain/cafe/service/CafeService.java
  src/main/java/com/gdg/coffee/domain/cafe/service/impl/CafeServiceImpl.java
Labels: ✨FEAT

#53 Feat/cafe
  src/main/java/com/gdg/coffee/domain/auth/controller/AuthController.java
  src/main/java/com/gdg/coffee/domain/pickup/repository/PickupRepositoryImpl.java
Labels: 🐞BUG

#54 Feat/pickup [Fix]: 500 error on pickup list APIs due to invalid fetchJoin with DTO projection
  src/main/java/com/gdg/coffee/domain/pickup/controller/PickupController.java
  src/main/java/com/gdg/coffee/domain/pickup/dto/PickupRequestDto.java
  src/main/java/com/gdg/coffee/domain/pickup/repository/PickupRepositoryImpl.java
Labels: 🐞BUG

#55 카페별 찌꺼기 목록 조회 api 추가 및 버그 수정
  src/main/java/com/gdg/coffee/domain/ground/controller/CoffeeGroundController.java
  src/main/java/com/gdg/coffee/domain/ground/service/CoffeeGroundService.java
  src/main/java/com/gdg/coffee/domain/ground/service/impl/CoffeeGroundServiceImpl.java
  src/main/java/com/gdg/coffee/global/config/SecurityConfig.java
Labels: ✂️CHORE

#58 [Feat] Swagger 설명 추가
  src/main/java/com/gdg/coffee/domain/solution/controller/SolutionController.java
Labels: 🚀API
